### ISSUE TITLE
Flex Plugin Deploy not working on windows

### ISSUE THREAD

**Issue by TheGarkine** [twilio-infra-as-code/twilio-pulumi-provider#11]
I currently have a problem with the flex plugin deploy on windows. Using the twilio cli with flex expansion fails if `shell: true` is not passed as an option to execFile.

Furthermore the --changelog parameter is not quoted and therefore the subsequent words are identified as individual arguments, causing the twilio CLI to error.

Edit: Made an Pull Request: #10

**Comment by kaiquelupo** [comment]
Hello @TheGarkine! Thank you for the pull request. We are reviewing the change and we will add it to the next version of the package. This should happen this week.

**Comment by TheGarkine** [comment]
Thank you tons, I am already working on another one to disable flex-plugins on delete. Maybe this one is coming today, so stay tuned!

**Comment by kaiquelupo** [comment]
Awesome @TheGarkine ! I hope the project is helping you out. I've requested some changes on your pull request so have a look please.

**Comment by kaiquelupo** [comment]
@TheGarkine your pull request was merged. We are planning to close all current issues to launch the next version of the package with your PR. Let me know if it makes sense for you

**Comment by TheGarkine** [comment]
Yeah thats fine, we have our own npm registry so I can use my own repository until then, would be great to switch to the official release soon though!
