### ISSUE TITLE
Delete Flex Plugin using Plugin API

### ISSUE THREAD

**Issue by kaiquelupo** [twilio-infra-as-code/twilio-pulumi-provider#12]
Currently the delete logic is removing the plugin source code from Serverless directly and it should be done by the Plugin API to guarantee consistency.

**Comment by TheGarkine** [comment]
@kaiquelupo Hey, its me again! #14 should fix this! Please review and give feedback would be great to have this included in the upcoming release!

**Comment by kaiquelupo** [comment]
Merged
