### ISSUE TITLE
Install Flex Plugins dependencies before any deployment

### ISSUE THREAD

**Issue by kaiquelupo** [twilio-infra-as-code/twilio-pulumi-provider#13]
Currently when deploying Flex Plugins we are not building it so we expect that the build command was ran before the up command. This should not have this dependency to make the experience more fluid.

**Comment by TheGarkine** [comment]
Going for it!

**Comment by TheGarkine** [comment]
Fixed by #14 .

**Comment by TheGarkine** [comment]
@kaiquelupo, do you think you can release soon, I am kinda blocked by that :/

**Comment by kaiquelupo** [comment]
Hey @TheGarkine, sorry for the delay! I will be working on all the pending requests during this weekend and I hope we will be able to publish the new version with the fixes in the beginning of next week.

**Comment by kaiquelupo** [comment]
Merged
