### ISSUE TITLE
Improve `findResourceByFriendlyName()`

### ISSUE THREAD

**Issue by vernig** [twilio-infra-as-code/twilio-pulumi-provider#9]
Currently the `findResourceByFriendlyName()` is using `friendlyName` to look for a resource. Some resources (e.g. TaskChannel) have both `friendlyName` and `uniqueName` as identifiers. 

This can potentially create an issue, because the only property that is currently checked is `freindlyName`. In order to see the potential issue, you can: 

* Set `FIND_BEFORE_CREATE=true`
* Execute the following:

```
'use strict';
const pulumi = require('@pulumi/pulumi');

const { Resource } = require('twilio-pulumi-provider');

const TaskChannel = new Resource('new-taskchannel', {
  resource: [
    'taskrouter',
    { workspaces: '<your workspace SID>' },
    'taskChannels',
  ],
  attributes: {
    friendlyName: 'SMS',
    uniqueName: 'sms2',
  },
});
```
Executing this *will not* change the `uniqueName` to `sms2` and *will not* trigger any error either.

**Comment by bermudezmt** [comment]
I'm confused about the distinction: `uniqueName` is distinct whereas `friendlyName` isn't? This is my conclusion after doing a cursory search on our API docs. How about finding a resource by SID?

**Comment by vernig** [comment]
@bermudezmt when creating a resource that has both properties, they are both required BUT only `uniqueName` needs to be unique. You can test it trying adding a channel with `uniqueName` as `sms` in a flex project: 

```
twilio api:taskrouter:v1:workspaces:task-channels:create --workspace-sid=<workspace_sid> --friendly-name SMS --unique-name sms
```

This will returns the following error: 

```
 » Error code 20001 from Twilio: Cannot create TaskChannel sms since a TaskChannel with the same UniqueName already exists. See https://www.twilio.com/docs/errors/20001 for more info.
```

On the other hand, if you create a TaskChannel with a new `uniqueName` but an existing `friendlyName` this is allowed, e.g.: 

```
twilio api:taskrouter:v1:workspaces:task-channels:create --workspace-sid=<workspace_sid> --friendly-name SMS --unique-name sms2
```

The above will create: 

![image](https://user-images.githubusercontent.com/54728384/127114744-3daff777-f4b7-4da6-8278-4609a186ec9a.png)

So in my opinion we should use `uniqueName` as identifier when that is an option. 

Let me know what you think.

**Comment by bermudezmt** [comment]
@vernig Are you thinking to mainly use the `friendlyName` but check for the existence of `uniqueName` and use that instead if it does?

Sorry I haven't followed up on the testing yet, but I trust your judgment on this.

**Comment by vernig** [comment]
> Are you thinking to mainly use the friendlyName but check for the existence of uniqueName and use that instead if it does?

You read my mind 😄

**Comment by vernig** [comment]
> What about having on more property on the object apart from resource and attributes?

@kaiquelupo as it is now, this function is used to search for existing resource and avoid Twilio throwing an error in creating them. For this specific case I don't really see the point of searching by other options. We should only use unique keys fort this (e.g. `friendlyName`, `uniqueName`, `sid`). 

Up to you if you want to create another function that search based on other attributes, but for this specific use case, it's not needed.

**Comment by kaiquelupo** [comment]
> > What about having on more property on the object apart from resource and attributes?
> 
> @kaiquelupo as it is now, this function is used to search for existing resource and avoid Twilio throwing an error in creating them. For this specific case I don't really see the point of searching by other options. We should only use unique keys fort this (e.g. `friendlyName`, `uniqueName`, `sid`).
> 
> Up to you if you want to create another function that search based on other attributes, but for this specific use case, it's not needed.

Yep, I understand. I am actually rethinking the use of the environment variable, maybe it would be better to have something like that: 

```
const TaskChannel = new Resource('new-taskchannel', {
  resource: [
    'taskrouter',
    { workspaces: '<your workspace SID>' },
    'taskChannels',
  ],
  attributes: {
    friendlyName: 'SMS',
    uniqueName: 'sms2',
  },
options: {
   findAndUseBy: "uniqueName"
}
});
```

And use options to actually not just this use case but also future ones.

**Comment by kaiquelupo** [comment]
> ```
> options: {
>    findAndUseBy: "uniqueName"
> }
> ```
> I'm really not a fan of adding too many options there. It makes using the provider more complicated. In my opinion, the provider should take care of properly handling the Twilio resources and possiby hide the complexity of them. This will increase adoptions (since developers don't need to know all the intricacies of Twilio APIs) 
> 
> What's the problem with simply changing the `findResourceByFriendlyName()` into a more generic `findResourceByUniqueKey()` and then check if the resource should be found using `uniqueName` or `friendlyName`? I can give a shot to implementing it 
> 

Right right, makes sense. If you don't mind to create a version of it, it would be great.

**Comment by kaiquelupo** [comment]
@vernig any news on that?
